# Generated by Django 5.2 on 2025-05-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infirmier',
            name='user',
        ),
        migrations.AddField(
            model_name='infirmier',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infirmier',
            name='nom',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infirmier',
            name='prenom',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
