# Generated by Django 5.2 on 2025-05-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_dossiermedical_user_alter_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='nom',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
