# Generated by Django 5.2 on 2025-05-16 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_email_patient_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
    ]
